server:
   context-path: /social
   port: 8081

spring:
   http:
      multipart:
         enabled: true
         file-size-threshold: 0
         location: C:/
         max-file-size: 20Mb
         max-request-size: 10Mb